### ISSUE TITLE
Wich status of nimue4?

### ISSUE THREAD

**Issue by R3D9477** [pragmagic/nimue4#29]
Hi! Is it possible to write a complete crossplatform 2D-game directly with Nim (without additional help from C/C++, etc..) to save one single code-base? Did it used for real projects (anndroid/html5)? Is there plans to support this library in the future? Thanks! (question on the [forum](https://forum.nim-lang.org/t/3563))?

**Comment by endragor** [comment]
Hi! I'm afraid this library is no longer actively maintained. It was used for a real project, but it didn't get released. You can implement the whole game using Nim, UE4 and this library, but you may need to add Nim wrappers for functionality that is missing in the library.

Also, at least about half a year ago UE4 wasn't really shining when it came to 2D performance on mobile - Slate (UI framework of UE4) had quite poor performance and you could find evidence of that all over UE4's forums or if you made your own simple benchmarks. I'm not sure if the situation has changed since then.

I'm not sure what your goal is, and what your experience level is with game development or with specific engines - I could give some advice based on that. Godot Engine with https://github.com/pragmagic/godot-nim could be an option for you if you would like to implement a 2D game fully in Nim. Godot is easier to learn and most likely it has everything you need for your game.

**Comment by R3D9477** [comment]
@endragor thank you for answer! I'm a very-very novice at game-dev, is Godot supports exporting project to Html5 and Android?

**Comment by endragor** [comment]
Yes it does, but there are still cases where HTML5 export does not work. However, they plan to make it fully supported in the next version.
